services:
  postgres:
    image: docker.io/postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invoicedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nodejs:
    image: docker.io/node:latest
    container_name: nodejs
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/invoicedb
    command: npm run dev
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app

volumes:
  postgres_data:
